#!/bin/bash

oldWd=$(pwd)

wdBase=$XDG_CACHE_HOME
if [[ -z $wdBase ]]; then
    wdBase="$HOME"/.cache
fi
wd="$wdBase"/aureus
mkdir -p $wd
cd $wd

jqFile="/usr/lib/aureus/aureus-jq"

fzfPreview="curl -s 'https://aur.archlinux.org/rpc/v5/info?arg[]={}' | jq -rf $jqFile > preview && cat preview"
fzfBind="enter:execute(rm -rf {} && git clone https://aur.archlinux.org/{}.git && cd {} && makepkg -si)+accept"

while getopts 'RQSUPC' opt; do
    case $opt in 
        R)
            if [[ -z $2 ]]; then
                pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(sudo pacman -Rsnc {})+accept'
            else
                sudo pacman -Rnsc $2
            fi
            ;;
        Q)
            if [[ -z $2 ]]; then
                pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)+accept'
            else
                pacman -Qil $2
            fi
            ;;
        S)
            if [[ -z $2 ]]; then
                curl -s https://aur.archlinux.org/packages.gz -O
                gzip -df packages.gz
                fzf --preview "$fzfPreview" --layout=reverse --bind "$fzfBind" < packages
            else
                echo checking whether "$2" can be installed via pacman...
                sudo pacman -S $2
                if [[ $? -eq 0 ]]; then
                    # package successfully installed via pacman
                    echo "$2" installed via pacman
                    continue
                fi
                echo could not install "$2" via pacman
                echo installing "$2" from the AUR...
                if [[ $2 =~ [*/~] ]]; then
                    # don't `rm -rf` anything that contains these characters, for obvious reasons
                    # AUR package names can contain `.`, fortunately rm refuses to remove `.` and `..`
                    continue
                fi
                if [[ -z $(git ls-remote https://aur.archlinux.org/"$2".git) ]]; then
                    echo "$2 isn't a package in the AUR - skipping"
                    continue
                fi
                if [[ -e "$2" ]]; then
                    read -p "remove cached package $wd/$2? [y/n] " confirmation
                    if [[ $confirmation != "y" ]]; then
                        continue
                    fi
                    rm -rf "$wd"/"$2"
                fi
                git clone -q https://aur.archlinux.org/"$2".git
                cd "$2"
                makepkg -si
            fi
            ;;
        U)
            pacman -Qm > foreign-packages
            while read -r line; do
                sudo -v # reset sudo timeout
                name=$(echo $line | sed -e 's/ .*//')
                version=$(echo $line | sed -e 's/.* //')
                if [[ $name =~ [*/~] ]]; then
                    # don't `rm -rf` anything that contains these characters, for obvious reasons
                    # AUR package names can contain `.`, fortunately rm refuses to remove `.` and `..`
                    continue
                fi
                if [[ -z $(git ls-remote https://aur.archlinux.org/"$name".git) ]]; then
                    echo "$name isn't a package in the AUR - skipping"
                    continue
                fi
                remoteVersion=$(curl -s "https://aur.archlinux.org/rpc/v5/info?arg[]=$name" | jq -r '.results[0].Version')
                if [[ $(vercmp $remoteVersion $version) -gt 0 ]]; then # vercmp (version comparison utility) is provided by pacman
                    echo "$name is outdated ($version) - updating to $remoteVersion"
                    rm -rf "$name"
                    git clone -q https://aur.archlinux.org/"$name".git
                    cd $name
                    yes | makepkg -si
                    cd $wd
                else
                    echo "$name is up to date ($version) - skipping"
                fi
            done < foreign-packages
            ;;
        P)
            sudo pacman -Syu
            ;;
        C)
            if [[ -n $wd ]]; then
                read -p "clear cache ($wd)? [y/n] " confirmation
                if [[ $confirmation != "y" ]]; then
                    continue
                fi
                rm -rf "$wd"/*
            fi
    esac
done

if [[ -z $1 ]]; then
    aureus -UP
fi

cd $oldWd
