#!/bin/bash

args=( "$@" )

oldWd=$(pwd)

wdBase=$XDG_CACHE_HOME
if [[ -z $wdBase ]]; then
    wdBase="$HOME"/.cache
fi
wd="$wdBase"/aureus
mkdir -p $wd
cd $wd

installAURPackage() {
    echo installing "$1" from the AUR...
    if [[ $1 =~ [*/~] ]]; then
        # don't `rm -rf` anything that contains these characters, for obvious reasons
        # AUR package names can contain `.`, fortunately rm refuses to remove `.` and `..`
        return 1
    fi
    if [[ -z $(git ls-remote https://aur.archlinux.org/"$1".git) ]]; then
        echo "$1 isn't a package in the AUR"
        return 1
    fi
    git clone -q https://aur.archlinux.org/"$1".git
    cd "$1"
    makepkg -si 2>&1 | tee makepkg-output # copy output to file
    if [[ "${PIPESTATUS[0]}" -ne 0 ]]; then
        # check dependencies by analysing makepkg-output
        echo "makepkg failed, checking dependencies..."
        deps=$(awk '{print $2}' makepkg-output | tr '\n' ' ' | sed -e 's/.*Missing //' -e 's/ERROR.*//' -e 's/[A-Z].* //')
        installMultiplePackages $deps
        installAURPackage $1
    fi
    cd "$wd"
}

installPackage() {
    if [[ -e "$1" ]]; then
        read -rp "remove cached package $wd/$1? [y/n] " confirmation
        if [[ $confirmation != "y" ]]; then
            cd "$1"
            makepkg -si
        fi
        rm -rf "$wd"/"$1"
    fi
    echo checking whether "$1" can be installed via pacman...
    sudo pacman -S $1
    if [[ $? -eq 0 ]]; then
        # package successfully installed via pacman
        echo "$1" installed via pacman
        return 0
    fi
    echo could not install "$1" via pacman
    installAURPackage "$1"
}

installMultiplePackages() {
    for name in "$@"; do
        echo $name
        installPackage $name
    done
}

removeMultiplePackages() {
    for name in "$@"; do
        sudo pacman -Rnsc $name
    done
}

jqFile="/usr/lib/aureus/aureus-jq"

fzfPreview="curl -s 'https://aur.archlinux.org/rpc/v5/info?arg[]={}' | jq -rf $jqFile > preview && cat preview"
fzfBind="enter:execute(aureus -S {})+accept"

while getopts 'RQSUPC' opt; do
    case $opt in 
        R)
            if [[ -z $2 ]]; then
                pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(sudo pacman -Rsnc {})+accept'
            else
                removeMultiplePackages "${args[@]:1}"
            fi
            ;;
        Q)
            if [[ -z $2 ]]; then
                pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)+accept'
            else
                pacman -Qil $2
            fi
            ;;
        S)
            if [[ -z $2 ]]; then
                curl -s https://aur.archlinux.org/packages.gz -O
                gzip -df packages.gz
                fzf --preview "$fzfPreview" --layout=reverse --bind "$fzfBind" < packages
            else
                installMultiplePackages "${args[@]:1}"
            fi
            ;;
        U)
            pacman -Qm > foreign-packages
            while read -r line; do
                sudo -v # reset sudo timeout
                name=$(echo $line | sed -e 's/ .*//')
                version=$(echo $line | sed -e 's/.* //')
                if [[ $name =~ [*/~] ]]; then
                    # don't `rm -rf` anything that contains these characters, for obvious reasons
                    # AUR package names can contain `.`, fortunately rm refuses to remove `.` and `..`
                    continue
                fi
                if [[ -z $(git ls-remote https://aur.archlinux.org/"$name".git) ]]; then
                    echo "$name isn't a package in the AUR - skipping"
                    continue
                fi
                remoteVersion=$(curl -s "https://aur.archlinux.org/rpc/v5/info?arg[]=$name" | jq -r '.results[0].Version')
                if [[ $(vercmp $remoteVersion $version) -gt 0 ]]; then # vercmp (version comparison utility) is provided by pacman
                    echo "$name is outdated ($version) - updating to $remoteVersion"
                    installAURPackage "$name"
                else
                    echo "$name is up to date ($version) - skipping"
                fi
            done < foreign-packages
            ;;
        P)
            sudo pacman -Syu
            ;;
        C)
            if [[ -n $wd ]]; then
                read -rp "clear cache ($wd)? [y/n] " confirmation
                if [[ $confirmation != "y" ]]; then
                    continue
                fi
                rm -rf "$wd"/*
            fi
            ;;
    esac
done

if [[ -z $1 ]]; then
    aureus -UP
fi

cd $oldWd
